# fly.toml app configuration file generated for oncheckin-server on 2023-07-05T15:17:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oncheckin-server"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
